version: '3.8'

services:
  web:
    build: .
    command: python /PycharmProjects/books/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/PycharmProjects/books
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - "DJANGO_SECRET_KEY=z+nul&ybmcfue9=b%4#e4*(e@aej8#z-!y1)d$$golt5l#d1*c("
      - "DJANGO_DEBUG=True"
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data: